# Drones

[[drone]]
id = 1
connected_node_ids = [101, 2, 4, 102]
pdr = 0.0

[[drone]]
id = 2
connected_node_ids = [1, 3, 103]
pdr = 0.0

[[drone]]
id = 3
connected_node_ids = [2, 201, 103]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [101, 1, 5, 102]
pdr = 0.0

[[drone]]
id = 5
connected_node_ids = [4, 201]
pdr = 0.0

# Client

[[client]]
id = 101
connected_drone_ids = [1, 4]


[[client]]
id = 102
connected_drone_ids = [1, 4]

[[client]]
id = 103
connected_drone_ids = [2, 4]

# Servers

[[server]]
id = 201
connected_drone_ids = [3, 5]