[[drone]]
id = 1
pdr = 0.1
connected_node_ids = [5, 6, 202]

[[drone]]
id = 2
pdr = 0.25
connected_node_ids = [5, 6]

[[drone]]
id = 3
pdr = 0.14
connected_node_ids = [7, 8]

[[drone]]
id = 4
pdr = 0.03
connected_node_ids = [7, 8, 201]

[[drone]]
id = 5
pdr = 0.05
connected_node_ids = [1, 2, 9, 100, 202]

[[drone]]
id = 6
pdr = 0.03
connected_node_ids = [1, 2, 10]

[[drone]]
id = 7
pdr = 0.05
connected_node_ids = [3, 4, 9]

[[drone]]
id = 8
pdr = 0.03
connected_node_ids = [3, 4, 10, 102, 201]

[[drone]]
id = 9
pdr = 0.14
connected_node_ids = [5, 7, 100, 200]

[[drone]]
id = 10
pdr = 0.1
connected_node_ids = [6, 8, 101, 200]

[[client]]
id = 100
connected_drone_ids = [9, 5]

[[client]]
id = 101
connected_drone_ids = [10]

[[client]]
id = 102
connected_drone_ids = [8]

[[server]]
id = 200
connected_drone_ids = [9, 10]

[[server]]
id = 201
connected_drone_ids = [4, 8]

[[server]]
id = 202
connected_drone_ids = [1, 5]
