[[drone]]
id = 1
pdr = 0.1
connected_node_ids = [2, 3, 100]

[[drone]]
id = 2
pdr = 0.25
connected_node_ids = [1, 4, 5]

[[drone]]
id = 3
pdr = 0.14
connected_node_ids = [1, 5, 6, 202]

[[drone]]
id = 4
pdr = 0.03
connected_node_ids = [2, 7, 8, 101]

[[drone]]
id = 5
pdr = 0.05
connected_node_ids = [2, 3, 8, 9, 201]

[[drone]]
id = 6
pdr = 0.03
connected_node_ids = [3, 9, 10, 102]

[[drone]]
id = 7
pdr = 0.05
connected_node_ids = [4, 200]

[[drone]]
id = 8
pdr = 0.03
connected_node_ids = [4, 5, 200]

[[drone]]
id = 9
pdr = 0.14
connected_node_ids = [5, 6, 201]

[[drone]]
id = 10
pdr = 0.1
connected_node_ids = [6, 202]

[[client]]
id = 100
connected_drone_ids = [1]

[[client]]
id = 101
connected_drone_ids = [4]

[[client]]
id = 102
connected_drone_ids = [6]

[[server]]
id = 200
connected_drone_ids = [7,8]

[[server]]
id = 201
connected_drone_ids = [5, 9]

[[server]]
id = 202
connected_drone_ids = [3, 10]
